apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app-18-dec
  annotations:
    mia-platform.eu/version: 14.4.1
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    fluentbit.io/parser: pino
  labels:
    app: azure-app-18-dec
    app.kubernetes.io/name: azure-app-18-dec
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: terraform-demo-18-dec
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app-18-dec
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        fluentbit.io/parser: pino
      labels:
        app: azure-app-18-dec
        app.kubernetes.io/name: azure-app-18-dec
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: terraform-demo-18-dec
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: DEV
        mia-platform.eu/tenant: b933f1ef-5b8e-4adf-a346-24a3b03d13e8
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
        - name: orca-ghcr
        - name: orca-google-registry
      terminationGracePeriodSeconds: 30
      serviceAccountName: azure-app-18-dec
      containers:
        - name: azure-app-18-dec
          image: nexus.mia-platform.eu/terraform-demo-18-dec/azure-app-18-dec
          imagePullPolicy: Always
          resources:
            limits:
              memory: 150Mi
              cpu: 100m
            requests:
              memory: 150Mi
              cpu: 100m
          volumeMounts: []
          ports:
            - name: http
              containerPort: 80
          args: []
          env:
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: MICROSERVICE_GATEWAY_SERVICE_NAME
              value: microservice-gateway
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: HTTP_PORT
              value: '3000'
            - name: USERID_HEADER_KEY
              value: miauserid
            - name: GROUPS_HEADER_KEY
              value: miausergroups
            - name: CLIENTTYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: USER_PROPERTIES_HEADER_KEY
              value: miauserproperties
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: http
              path: /-/healthz
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes: []
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
