apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../configuration
  - azure-app-18-dec.deployment.yml
  - azure-app-18-dec.service.yml
  - azure-app-18-dec.serviceaccount.yml
